# Generated by Django 5.0.6 on 2024-08-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prices',
            new_name='price',
        ),
    ]
