# Generated by Django 5.0.6 on 2024-08-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_prices_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prices',
        ),
    ]
